/**
 * lthn API
 * Lethean Desktop HTTP gateway — same surface the WebView reaches via Wails bindings, exposed to external clients and the plugin market.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Meta } from './meta';
import { PostV1RunnerChat200ResponseData } from './postV1RunnerChat200ResponseData';


export interface PostV1RunnerChat200Response { 
    data?: PostV1RunnerChat200ResponseData;
    error?: Error;
    meta?: Meta;
    success: boolean;
}
