/**
 * lthn API
 * Lethean Desktop HTTP gateway — same surface the WebView reaches via Wails bindings, exposed to external clients and the plugin market.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Observable } from 'rxjs/Observable';

import { map } from 'rxjs/operators';
import IHttpClient from '../IHttpClient';
import { inject, injectable } from 'inversify';
import { IAPIConfiguration } from '../IAPIConfiguration';
import { Headers } from '../Headers';
import HttpResponse from '../HttpResponse';

import { GetHealth429Response } from '../model/getHealth429Response';
import { GetV1RunnerModels200Response } from '../model/getV1RunnerModels200Response';
import { PostV1RunnerChat200Response } from '../model/postV1RunnerChat200Response';
import { PostV1RunnerChatRequest } from '../model/postV1RunnerChatRequest';
import { PostV1RunnerGenerateRequest } from '../model/postV1RunnerGenerateRequest';

import { COLLECTION_FORMATS }  from '../variables';



@injectable()
export class RunnerService {
    private basePath: string = 'http://localhost';

    constructor(@inject('IApiHttpClient') private httpClient: IHttpClient,
        @inject('IAPIConfiguration') private APIConfiguration: IAPIConfiguration ) {
        if(this.APIConfiguration.basePath)
            this.basePath = this.APIConfiguration.basePath;
    }

    /**
     * List configured runner model routes
     * 
     
     */
    public getV1RunnerModels(observe?: 'body', headers?: Headers): Observable<GetV1RunnerModels200Response>;
    public getV1RunnerModels(observe?: 'response', headers?: Headers): Observable<HttpResponse<GetV1RunnerModels200Response>>;
    public getV1RunnerModels(observe: any = 'body', headers: Headers = {}): Observable<any> {
        // authentication (bearerAuth) required
        headers['Accept'] = 'application/json';

        const response: Observable<HttpResponse<GetV1RunnerModels200Response>> = this.httpClient.get(`${this.basePath}/v1/runner/models`, headers);
        if (observe === 'body') {
               return response.pipe(
                   map((httpResponse: HttpResponse) => <GetV1RunnerModels200Response>(httpResponse.response))
               );
        }
        return response;
    }


    /**
     * Multi-turn chat completion
     * 
     * @param postV1RunnerChatRequest 
     
     */
    public postV1RunnerChat(postV1RunnerChatRequest: PostV1RunnerChatRequest, observe?: 'body', headers?: Headers): Observable<PostV1RunnerChat200Response>;
    public postV1RunnerChat(postV1RunnerChatRequest: PostV1RunnerChatRequest, observe?: 'response', headers?: Headers): Observable<HttpResponse<PostV1RunnerChat200Response>>;
    public postV1RunnerChat(postV1RunnerChatRequest: PostV1RunnerChatRequest, observe: any = 'body', headers: Headers = {}): Observable<any> {
        if (postV1RunnerChatRequest === null || postV1RunnerChatRequest === undefined){
            throw new Error('Required parameter postV1RunnerChatRequest was null or undefined when calling postV1RunnerChat.');
        }

        // authentication (bearerAuth) required
        headers['Accept'] = 'application/json';
        headers['Content-Type'] = 'application/json';

        const response: Observable<HttpResponse<PostV1RunnerChat200Response>> = this.httpClient.post(`${this.basePath}/v1/runner/chat`, postV1RunnerChatRequest , headers);
        if (observe === 'body') {
               return response.pipe(
                   map((httpResponse: HttpResponse) => <PostV1RunnerChat200Response>(httpResponse.response))
               );
        }
        return response;
    }


    /**
     * Single-prompt generation
     * 
     * @param postV1RunnerGenerateRequest 
     
     */
    public postV1RunnerGenerate(postV1RunnerGenerateRequest: PostV1RunnerGenerateRequest, observe?: 'body', headers?: Headers): Observable<PostV1RunnerChat200Response>;
    public postV1RunnerGenerate(postV1RunnerGenerateRequest: PostV1RunnerGenerateRequest, observe?: 'response', headers?: Headers): Observable<HttpResponse<PostV1RunnerChat200Response>>;
    public postV1RunnerGenerate(postV1RunnerGenerateRequest: PostV1RunnerGenerateRequest, observe: any = 'body', headers: Headers = {}): Observable<any> {
        if (postV1RunnerGenerateRequest === null || postV1RunnerGenerateRequest === undefined){
            throw new Error('Required parameter postV1RunnerGenerateRequest was null or undefined when calling postV1RunnerGenerate.');
        }

        // authentication (bearerAuth) required
        headers['Accept'] = 'application/json';
        headers['Content-Type'] = 'application/json';

        const response: Observable<HttpResponse<PostV1RunnerChat200Response>> = this.httpClient.post(`${this.basePath}/v1/runner/generate`, postV1RunnerGenerateRequest , headers);
        if (observe === 'body') {
               return response.pipe(
                   map((httpResponse: HttpResponse) => <PostV1RunnerChat200Response>(httpResponse.response))
               );
        }
        return response;
    }

}
