/**
 * lthn API
 * Lethean Desktop HTTP gateway — same surface the WebView reaches via Wails bindings, exposed to external clients and the plugin market.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Observable } from 'rxjs/Observable';

import { map } from 'rxjs/operators';
import IHttpClient from '../IHttpClient';
import { inject, injectable } from 'inversify';
import { IAPIConfiguration } from '../IAPIConfiguration';
import { Headers } from '../Headers';
import HttpResponse from '../HttpResponse';

import { GetHealth200Response } from '../model/getHealth200Response';
import { GetHealth429Response } from '../model/getHealth429Response';

import { COLLECTION_FORMATS }  from '../variables';



@injectable()
export class SystemService {
    private basePath: string = 'http://localhost';

    constructor(@inject('IApiHttpClient') private httpClient: IHttpClient,
        @inject('IAPIConfiguration') private APIConfiguration: IAPIConfiguration ) {
        if(this.APIConfiguration.basePath)
            this.basePath = this.APIConfiguration.basePath;
    }

    /**
     * Health check
     * Returns server health status
     
     */
    public getHealth(observe?: 'body', headers?: Headers): Observable<GetHealth200Response>;
    public getHealth(observe?: 'response', headers?: Headers): Observable<HttpResponse<GetHealth200Response>>;
    public getHealth(observe: any = 'body', headers: Headers = {}): Observable<any> {
        headers['Accept'] = 'application/json';

        const response: Observable<HttpResponse<GetHealth200Response>> = this.httpClient.get(`${this.basePath}/health`, headers);
        if (observe === 'body') {
               return response.pipe(
                   map((httpResponse: HttpResponse) => <GetHealth200Response>(httpResponse.response))
               );
        }
        return response;
    }

}
